name: "OpsGuard AI"
description: "AI-powered DevOps guardian for automated code review and security analysis"
author: "Your Name"

branding:
  icon: "shield"
  color: "blue"

inputs:
  github_token:
    description: "GitHub token for API access"
    required: true
  openai_api_key:
    description: "OpenAI API key for AI analysis"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
